version: "3"
services:
  eduplanpro:
    build: .
    ports:
      - "3001:3001"
  postgres:
    image: postgres:17
    environment:
      - POSTGRES_PASSWORD=123
    ports:
      - "5432:5432"
    volumes:
      - backend:/var/lib/pgsql/data
volumes:
  backend: {}
