--
-- PostgreSQL database dump
--

-- Dumped from database version 17.0
-- Dumped by pg_dump version 17.0

-- Started on 2024-10-14 16:50:33

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

DROP DATABASE "EDUPLANPRO";
--
-- TOC entry 5020 (class 1262 OID 16388)
-- Name: EDUPLANPRO; Type: DATABASE; Schema: -; Owner: postgres
--

CREATE DATABASE "EDUPLANPRO" WITH TEMPLATE = template0 ENCODING = 'UTF8' LOCALE_PROVIDER = libc LOCALE = 'Spanish_Spain.1252';


ALTER DATABASE "EDUPLANPRO" OWNER TO postgres;

\connect "EDUPLANPRO"

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 4 (class 2615 OID 2200)
-- Name: public; Type: SCHEMA; Schema: -; Owner: pg_database_owner
--

CREATE SCHEMA public;


ALTER SCHEMA public OWNER TO pg_database_owner;

--
-- TOC entry 5021 (class 0 OID 0)
-- Dependencies: 4
-- Name: SCHEMA public; Type: COMMENT; Schema: -; Owner: pg_database_owner
--

COMMENT ON SCHEMA public IS 'standard public schema';


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 223 (class 1259 OID 16453)
-- Name: EPPM_CAREER; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."EPPM_CAREER" (
    "DSC_CARRER" text NOT NULL,
    "DSC_CODE" text,
    "ID_SCHOOL" integer,
    "UPDATED_BY" integer NOT NULL,
    "UPDATED AT" timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    "CREATED_AT" timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    "STATE" "char" DEFAULT '1'::"char",
    "ID_CAREER" integer NOT NULL
);


ALTER TABLE public."EPPM_CAREER" OWNER TO postgres;

--
-- TOC entry 244 (class 1259 OID 16561)
-- Name: EPPM_CAREER_ID_CAREER_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."EPPM_CAREER" ALTER COLUMN "ID_CAREER" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."EPPM_CAREER_ID_CAREER_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 227 (class 1259 OID 16472)
-- Name: EPPM_COURSE_PROGRAM; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."EPPM_COURSE_PROGRAM" (
    "ID_COURSE_PROGRAM" integer NOT NULL,
    "DSC_NAME" text NOT NULL,
    "DAT_YEAR" date,
    "ID_STUDY_PLAN" integer,
    "NRC" text,
    "CICLE" "char",
    "NUM_CREDITS" numeric,
    "SIGNATURE" "char",
    "UPDATED_BY" integer NOT NULL,
    "UPDATED_AT" timestamp without time zone,
    "CREATED_AT" timestamp without time zone,
    "PDF_URL" text,
    "STATE" "char"
);


ALTER TABLE public."EPPM_COURSE_PROGRAM" OWNER TO postgres;

--
-- TOC entry 226 (class 1259 OID 16471)
-- Name: EPPM_COURSE_PROGRAM_ID_COURSE_PROGRAM_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public."EPPM_COURSE_PROGRAM_ID_COURSE_PROGRAM_seq"
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public."EPPM_COURSE_PROGRAM_ID_COURSE_PROGRAM_seq" OWNER TO postgres;

--
-- TOC entry 5022 (class 0 OID 0)
-- Dependencies: 226
-- Name: EPPM_COURSE_PROGRAM_ID_COURSE_PROGRAM_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public."EPPM_COURSE_PROGRAM_ID_COURSE_PROGRAM_seq" OWNED BY public."EPPM_COURSE_PROGRAM"."ID_COURSE_PROGRAM";


--
-- TOC entry 245 (class 1259 OID 16570)
-- Name: EPPM_COURSE_PROGRAM_ID_COURSE_PROGRAM_seq1; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."EPPM_COURSE_PROGRAM" ALTER COLUMN "ID_COURSE_PROGRAM" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."EPPM_COURSE_PROGRAM_ID_COURSE_PROGRAM_seq1"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 220 (class 1259 OID 16435)
-- Name: EPPM_FACULTY; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."EPPM_FACULTY" (
    "ID_FACULTY" integer NOT NULL,
    "DSC_FACULTY" text,
    "UPDATED_BY" integer NOT NULL,
    "UPDATED_AT" timestamp without time zone,
    "CREATED_AT" timestamp without time zone,
    "STATE" "char"
);


ALTER TABLE public."EPPM_FACULTY" OWNER TO postgres;

--
-- TOC entry 219 (class 1259 OID 16434)
-- Name: EPPM_FACULTY_ID_FACULTY_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public."EPPM_FACULTY_ID_FACULTY_seq"
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public."EPPM_FACULTY_ID_FACULTY_seq" OWNER TO postgres;

--
-- TOC entry 5023 (class 0 OID 0)
-- Dependencies: 219
-- Name: EPPM_FACULTY_ID_FACULTY_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public."EPPM_FACULTY_ID_FACULTY_seq" OWNED BY public."EPPM_FACULTY"."ID_FACULTY";


--
-- TOC entry 246 (class 1259 OID 16571)
-- Name: EPPM_FACULTY_ID_FACULTY_seq1; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."EPPM_FACULTY" ALTER COLUMN "ID_FACULTY" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."EPPM_FACULTY_ID_FACULTY_seq1"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 231 (class 1259 OID 16490)
-- Name: EPPM_PERSON; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."EPPM_PERSON" (
    "ID_PERSON" integer NOT NULL,
    "DSC_NAME" text NOT NULL,
    "DSC_SECOND_NAME" text NOT NULL,
    "IDCARD" text NOT NULL,
    "UPDATED_BY" integer,
    "UPDATED_AT" timestamp without time zone,
    "CREATED_AT" timestamp without time zone,
    "STATE" "char"
);


ALTER TABLE public."EPPM_PERSON" OWNER TO postgres;

--
-- TOC entry 230 (class 1259 OID 16489)
-- Name: EPPM_PERSON_ID_PERSON_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public."EPPM_PERSON_ID_PERSON_seq"
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public."EPPM_PERSON_ID_PERSON_seq" OWNER TO postgres;

--
-- TOC entry 5024 (class 0 OID 0)
-- Dependencies: 230
-- Name: EPPM_PERSON_ID_PERSON_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public."EPPM_PERSON_ID_PERSON_seq" OWNED BY public."EPPM_PERSON"."ID_PERSON";


--
-- TOC entry 247 (class 1259 OID 16572)
-- Name: EPPM_PERSON_ID_PERSON_seq1; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."EPPM_PERSON" ALTER COLUMN "ID_PERSON" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."EPPM_PERSON_ID_PERSON_seq1"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 218 (class 1259 OID 16425)
-- Name: EPPM_PHONE; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."EPPM_PHONE" (
    "ID_PHONE" integer NOT NULL,
    "NUM_PHONE_NUMBER" text NOT NULL,
    "UPDATE_BY" integer NOT NULL,
    "UPDATE_AT" timestamp without time zone,
    "CREATED_AT" time without time zone,
    "STATE" "char" DEFAULT '1'::"char"
);


ALTER TABLE public."EPPM_PHONE" OWNER TO postgres;

--
-- TOC entry 217 (class 1259 OID 16424)
-- Name: EPPM_PHONE_ID_PHONE_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public."EPPM_PHONE_ID_PHONE_seq"
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public."EPPM_PHONE_ID_PHONE_seq" OWNER TO postgres;

--
-- TOC entry 5025 (class 0 OID 0)
-- Dependencies: 217
-- Name: EPPM_PHONE_ID_PHONE_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public."EPPM_PHONE_ID_PHONE_seq" OWNED BY public."EPPM_PHONE"."ID_PHONE";


--
-- TOC entry 248 (class 1259 OID 16573)
-- Name: EPPM_PHONE_ID_PHONE_seq1; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."EPPM_PHONE" ALTER COLUMN "ID_PHONE" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."EPPM_PHONE_ID_PHONE_seq1"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 235 (class 1259 OID 16508)
-- Name: EPPM_ROL; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."EPPM_ROL" (
    "ID_ROL" integer NOT NULL,
    "DSC_NAME" text NOT NULL,
    "DSC_DESCRIPTION" text,
    "UPDATED_BY" integer NOT NULL,
    "UPDATED_AT" timestamp without time zone,
    "CREATED_AT" timestamp without time zone,
    "STATE" "char"
);


ALTER TABLE public."EPPM_ROL" OWNER TO postgres;

--
-- TOC entry 234 (class 1259 OID 16507)
-- Name: EPPM_ROL_ID_ROL_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public."EPPM_ROL_ID_ROL_seq"
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public."EPPM_ROL_ID_ROL_seq" OWNER TO postgres;

--
-- TOC entry 5026 (class 0 OID 0)
-- Dependencies: 234
-- Name: EPPM_ROL_ID_ROL_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public."EPPM_ROL_ID_ROL_seq" OWNED BY public."EPPM_ROL"."ID_ROL";


--
-- TOC entry 249 (class 1259 OID 16574)
-- Name: EPPM_ROL_ID_ROL_seq1; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."EPPM_ROL" ALTER COLUMN "ID_ROL" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."EPPM_ROL_ID_ROL_seq1"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 222 (class 1259 OID 16444)
-- Name: EPPM_SCHOOL; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."EPPM_SCHOOL" (
    "ID_SCHOOL" integer NOT NULL,
    "DSC_SCHOOL" text NOT NULL,
    "ID_FACULTY" integer,
    "UPDATED_BY" integer,
    "CREATED_AT" timestamp with time zone,
    "UPDATED_AT" time without time zone,
    "STATE" "char"
);


ALTER TABLE public."EPPM_SCHOOL" OWNER TO postgres;

--
-- TOC entry 221 (class 1259 OID 16443)
-- Name: EPPM_SCHOOL_ID_SCHOOL_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public."EPPM_SCHOOL_ID_SCHOOL_seq"
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public."EPPM_SCHOOL_ID_SCHOOL_seq" OWNER TO postgres;

--
-- TOC entry 5027 (class 0 OID 0)
-- Dependencies: 221
-- Name: EPPM_SCHOOL_ID_SCHOOL_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public."EPPM_SCHOOL_ID_SCHOOL_seq" OWNED BY public."EPPM_SCHOOL"."ID_SCHOOL";


--
-- TOC entry 250 (class 1259 OID 16575)
-- Name: EPPM_SCHOOL_ID_SCHOOL_seq1; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."EPPM_SCHOOL" ALTER COLUMN "ID_SCHOOL" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."EPPM_SCHOOL_ID_SCHOOL_seq1"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 225 (class 1259 OID 16462)
-- Name: EPPM_STUDY_PLAN; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."EPPM_STUDY_PLAN" (
    "ID_STUDY_PLAN" integer NOT NULL,
    "DSC_NAME" text NOT NULL,
    "DAT_INIT" date,
    "DAT_MAX" date,
    "ID_CAREER" integer,
    "UPDATED_BY" integer NOT NULL,
    "UPDATED_AT" timestamp without time zone,
    "CREATED_AT" timestamp without time zone,
    "PDF_URL" text,
    "STATE" "char"
);


ALTER TABLE public."EPPM_STUDY_PLAN" OWNER TO postgres;

--
-- TOC entry 224 (class 1259 OID 16461)
-- Name: EPPM_STUDY_PLAN_ID_STUDY_PLAN_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public."EPPM_STUDY_PLAN_ID_STUDY_PLAN_seq"
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public."EPPM_STUDY_PLAN_ID_STUDY_PLAN_seq" OWNER TO postgres;

--
-- TOC entry 5028 (class 0 OID 0)
-- Dependencies: 224
-- Name: EPPM_STUDY_PLAN_ID_STUDY_PLAN_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public."EPPM_STUDY_PLAN_ID_STUDY_PLAN_seq" OWNED BY public."EPPM_STUDY_PLAN"."ID_STUDY_PLAN";


--
-- TOC entry 251 (class 1259 OID 16576)
-- Name: EPPM_STUDY_PLAN_ID_STUDY_PLAN_seq1; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."EPPM_STUDY_PLAN" ALTER COLUMN "ID_STUDY_PLAN" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."EPPM_STUDY_PLAN_ID_STUDY_PLAN_seq1"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 229 (class 1259 OID 16481)
-- Name: EPPM_TEACHER; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."EPPM_TEACHER" (
    "ID_TEACHER" integer NOT NULL,
    "ID_PERSON" integer,
    "EMAIL" text NOT NULL,
    "UPDATED_BY" integer,
    "UPDATED_AT" timestamp without time zone,
    "CREATED_AT" timestamp without time zone,
    "STATE" "char"
);


ALTER TABLE public."EPPM_TEACHER" OWNER TO postgres;

--
-- TOC entry 228 (class 1259 OID 16480)
-- Name: EPPM_TEACHER_ID_TEACHER_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public."EPPM_TEACHER_ID_TEACHER_seq"
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public."EPPM_TEACHER_ID_TEACHER_seq" OWNER TO postgres;

--
-- TOC entry 5029 (class 0 OID 0)
-- Dependencies: 228
-- Name: EPPM_TEACHER_ID_TEACHER_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public."EPPM_TEACHER_ID_TEACHER_seq" OWNED BY public."EPPM_TEACHER"."ID_TEACHER";


--
-- TOC entry 252 (class 1259 OID 16577)
-- Name: EPPM_TEACHER_ID_TEACHER_seq1; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."EPPM_TEACHER" ALTER COLUMN "ID_TEACHER" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."EPPM_TEACHER_ID_TEACHER_seq1"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 233 (class 1259 OID 16499)
-- Name: EPPM_USER; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."EPPM_USER" (
    "ID_USER" integer NOT NULL,
    "ID_PERSON" integer,
    "ID_ROL" integer,
    "PASSWORD" text NOT NULL,
    "UPDATED_BY" integer NOT NULL,
    "UPDATED_AT" timestamp without time zone,
    "CREATED_AT" timestamp without time zone,
    "STATE" "char",
    "ID_PREFERENCES" integer
);


ALTER TABLE public."EPPM_USER" OWNER TO postgres;

--
-- TOC entry 232 (class 1259 OID 16498)
-- Name: EPPM_USER_ID_USER_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public."EPPM_USER_ID_USER_seq"
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public."EPPM_USER_ID_USER_seq" OWNER TO postgres;

--
-- TOC entry 5030 (class 0 OID 0)
-- Dependencies: 232
-- Name: EPPM_USER_ID_USER_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public."EPPM_USER_ID_USER_seq" OWNED BY public."EPPM_USER"."ID_USER";


--
-- TOC entry 253 (class 1259 OID 16578)
-- Name: EPPM_USER_ID_USER_seq1; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."EPPM_USER" ALTER COLUMN "ID_USER" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."EPPM_USER_ID_USER_seq1"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 243 (class 1259 OID 16538)
-- Name: EPPP_PREFERENCES; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."EPPP_PREFERENCES" (
    "ID_PREFERENCES" integer NOT NULL,
    "ID_USER" integer,
    "PREFERENCES" json
);


ALTER TABLE public."EPPP_PREFERENCES" OWNER TO postgres;

--
-- TOC entry 242 (class 1259 OID 16537)
-- Name: EPPP_PREFERENCES_ID_PREFERENCES_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public."EPPP_PREFERENCES_ID_PREFERENCES_seq"
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public."EPPP_PREFERENCES_ID_PREFERENCES_seq" OWNER TO postgres;

--
-- TOC entry 5031 (class 0 OID 0)
-- Dependencies: 242
-- Name: EPPP_PREFERENCES_ID_PREFERENCES_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public."EPPP_PREFERENCES_ID_PREFERENCES_seq" OWNED BY public."EPPP_PREFERENCES"."ID_PREFERENCES";


--
-- TOC entry 254 (class 1259 OID 16580)
-- Name: EPPP_PREFERENCES_ID_PREFERENCES_seq1; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."EPPP_PREFERENCES" ALTER COLUMN "ID_PREFERENCES" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."EPPP_PREFERENCES_ID_PREFERENCES_seq1"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 241 (class 1259 OID 16531)
-- Name: EPPT_FACULTY_PHONE; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."EPPT_FACULTY_PHONE" (
    "ID_FACULTY_PHONE" integer NOT NULL,
    "ID_FACULTY" integer,
    "ID_PHONE" integer
);


ALTER TABLE public."EPPT_FACULTY_PHONE" OWNER TO postgres;

--
-- TOC entry 240 (class 1259 OID 16530)
-- Name: EPPT_FACULTY_PHONE_ID_FACULTY_PHONE_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public."EPPT_FACULTY_PHONE_ID_FACULTY_PHONE_seq"
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public."EPPT_FACULTY_PHONE_ID_FACULTY_PHONE_seq" OWNER TO postgres;

--
-- TOC entry 5032 (class 0 OID 0)
-- Dependencies: 240
-- Name: EPPT_FACULTY_PHONE_ID_FACULTY_PHONE_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public."EPPT_FACULTY_PHONE_ID_FACULTY_PHONE_seq" OWNED BY public."EPPT_FACULTY_PHONE"."ID_FACULTY_PHONE";


--
-- TOC entry 255 (class 1259 OID 16581)
-- Name: EPPT_FACULTY_PHONE_ID_FACULTY_PHONE_seq1; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."EPPT_FACULTY_PHONE" ALTER COLUMN "ID_FACULTY_PHONE" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."EPPT_FACULTY_PHONE_ID_FACULTY_PHONE_seq1"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 239 (class 1259 OID 16524)
-- Name: EPPT_PHONE_SCHOOL; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."EPPT_PHONE_SCHOOL" (
    "ID_PHONE_SCHOOL" integer NOT NULL,
    "ID_SCHOOL" integer,
    "ID_PHONE" integer
);


ALTER TABLE public."EPPT_PHONE_SCHOOL" OWNER TO postgres;

--
-- TOC entry 238 (class 1259 OID 16523)
-- Name: EPPT_PHONE_SCHOOL_ID_PHONE_SCHOOL_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public."EPPT_PHONE_SCHOOL_ID_PHONE_SCHOOL_seq"
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public."EPPT_PHONE_SCHOOL_ID_PHONE_SCHOOL_seq" OWNER TO postgres;

--
-- TOC entry 5033 (class 0 OID 0)
-- Dependencies: 238
-- Name: EPPT_PHONE_SCHOOL_ID_PHONE_SCHOOL_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public."EPPT_PHONE_SCHOOL_ID_PHONE_SCHOOL_seq" OWNED BY public."EPPT_PHONE_SCHOOL"."ID_PHONE_SCHOOL";


--
-- TOC entry 256 (class 1259 OID 16582)
-- Name: EPPT_PHONE_SCHOOL_ID_PHONE_SCHOOL_seq1; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."EPPT_PHONE_SCHOOL" ALTER COLUMN "ID_PHONE_SCHOOL" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."EPPT_PHONE_SCHOOL_ID_PHONE_SCHOOL_seq1"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 237 (class 1259 OID 16517)
-- Name: EPPT_TEACHER_COURSE_PROGRAM; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."EPPT_TEACHER_COURSE_PROGRAM" (
    "ID_TEACHER_COUSE_PROGRAM" integer NOT NULL,
    "ID_TEACHER" integer,
    "ID_COURSE_PROGRAM" integer
);


ALTER TABLE public."EPPT_TEACHER_COURSE_PROGRAM" OWNER TO postgres;

--
-- TOC entry 236 (class 1259 OID 16516)
-- Name: EPPT_TEACHER_COURSE_PROGRAM_ID_TEACHER_COUSE_PROGRAM_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public."EPPT_TEACHER_COURSE_PROGRAM_ID_TEACHER_COUSE_PROGRAM_seq"
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public."EPPT_TEACHER_COURSE_PROGRAM_ID_TEACHER_COUSE_PROGRAM_seq" OWNER TO postgres;

--
-- TOC entry 5034 (class 0 OID 0)
-- Dependencies: 236
-- Name: EPPT_TEACHER_COURSE_PROGRAM_ID_TEACHER_COUSE_PROGRAM_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public."EPPT_TEACHER_COURSE_PROGRAM_ID_TEACHER_COUSE_PROGRAM_seq" OWNED BY public."EPPT_TEACHER_COURSE_PROGRAM"."ID_TEACHER_COUSE_PROGRAM";


--
-- TOC entry 257 (class 1259 OID 16583)
-- Name: EPPT_TEACHER_COURSE_PROGRAM_ID_TEACHER_COUSE_PROGRAM_seq1; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."EPPT_TEACHER_COURSE_PROGRAM" ALTER COLUMN "ID_TEACHER_COUSE_PROGRAM" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."EPPT_TEACHER_COURSE_PROGRAM_ID_TEACHER_COUSE_PROGRAM_seq1"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 4980 (class 0 OID 16453)
-- Dependencies: 223
-- Data for Name: EPPM_CAREER; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 4984 (class 0 OID 16472)
-- Dependencies: 227
-- Data for Name: EPPM_COURSE_PROGRAM; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 4977 (class 0 OID 16435)
-- Dependencies: 220
-- Data for Name: EPPM_FACULTY; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 4988 (class 0 OID 16490)
-- Dependencies: 231
-- Data for Name: EPPM_PERSON; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public."EPPM_PERSON" VALUES (1, 'root', 'root', 'root', NULL, '2024-10-14 13:26:21.525194', '2024-10-14 13:26:21.525194', '1');


--
-- TOC entry 4975 (class 0 OID 16425)
-- Dependencies: 218
-- Data for Name: EPPM_PHONE; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public."EPPM_PHONE" VALUES (1, '12345678', 1, '2024-10-13 17:49:05.468851', '17:49:05.468851', '1');


--
-- TOC entry 4992 (class 0 OID 16508)
-- Dependencies: 235
-- Data for Name: EPPM_ROL; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public."EPPM_ROL" VALUES (1, 'ROOT', 'ROOT', 1, '2024-10-14 13:29:31.991002', '2024-10-14 13:29:31.991002', '1');


--
-- TOC entry 4979 (class 0 OID 16444)
-- Dependencies: 222
-- Data for Name: EPPM_SCHOOL; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 4982 (class 0 OID 16462)
-- Dependencies: 225
-- Data for Name: EPPM_STUDY_PLAN; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 4986 (class 0 OID 16481)
-- Dependencies: 229
-- Data for Name: EPPM_TEACHER; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 4990 (class 0 OID 16499)
-- Dependencies: 233
-- Data for Name: EPPM_USER; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public."EPPM_USER" VALUES (1, 1, 1, 'root', 1, '2024-10-14 13:32:29.512893', '2024-10-14 13:32:29.512893', '1', NULL);


--
-- TOC entry 5000 (class 0 OID 16538)
-- Dependencies: 243
-- Data for Name: EPPP_PREFERENCES; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 4998 (class 0 OID 16531)
-- Dependencies: 241
-- Data for Name: EPPT_FACULTY_PHONE; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 4996 (class 0 OID 16524)
-- Dependencies: 239
-- Data for Name: EPPT_PHONE_SCHOOL; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 4994 (class 0 OID 16517)
-- Dependencies: 237
-- Data for Name: EPPT_TEACHER_COURSE_PROGRAM; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 5035 (class 0 OID 0)
-- Dependencies: 244
-- Name: EPPM_CAREER_ID_CAREER_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."EPPM_CAREER_ID_CAREER_seq"', 5, true);


--
-- TOC entry 5036 (class 0 OID 0)
-- Dependencies: 226
-- Name: EPPM_COURSE_PROGRAM_ID_COURSE_PROGRAM_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."EPPM_COURSE_PROGRAM_ID_COURSE_PROGRAM_seq"', 1, false);


--
-- TOC entry 5037 (class 0 OID 0)
-- Dependencies: 245
-- Name: EPPM_COURSE_PROGRAM_ID_COURSE_PROGRAM_seq1; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."EPPM_COURSE_PROGRAM_ID_COURSE_PROGRAM_seq1"', 1, false);


--
-- TOC entry 5038 (class 0 OID 0)
-- Dependencies: 219
-- Name: EPPM_FACULTY_ID_FACULTY_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."EPPM_FACULTY_ID_FACULTY_seq"', 1, false);


--
-- TOC entry 5039 (class 0 OID 0)
-- Dependencies: 246
-- Name: EPPM_FACULTY_ID_FACULTY_seq1; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."EPPM_FACULTY_ID_FACULTY_seq1"', 1, false);


--
-- TOC entry 5040 (class 0 OID 0)
-- Dependencies: 230
-- Name: EPPM_PERSON_ID_PERSON_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."EPPM_PERSON_ID_PERSON_seq"', 1, false);


--
-- TOC entry 5041 (class 0 OID 0)
-- Dependencies: 247
-- Name: EPPM_PERSON_ID_PERSON_seq1; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."EPPM_PERSON_ID_PERSON_seq1"', 1, true);


--
-- TOC entry 5042 (class 0 OID 0)
-- Dependencies: 217
-- Name: EPPM_PHONE_ID_PHONE_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."EPPM_PHONE_ID_PHONE_seq"', 1, true);


--
-- TOC entry 5043 (class 0 OID 0)
-- Dependencies: 248
-- Name: EPPM_PHONE_ID_PHONE_seq1; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."EPPM_PHONE_ID_PHONE_seq1"', 1, false);


--
-- TOC entry 5044 (class 0 OID 0)
-- Dependencies: 234
-- Name: EPPM_ROL_ID_ROL_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."EPPM_ROL_ID_ROL_seq"', 1, false);


--
-- TOC entry 5045 (class 0 OID 0)
-- Dependencies: 249
-- Name: EPPM_ROL_ID_ROL_seq1; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."EPPM_ROL_ID_ROL_seq1"', 1, true);


--
-- TOC entry 5046 (class 0 OID 0)
-- Dependencies: 221
-- Name: EPPM_SCHOOL_ID_SCHOOL_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."EPPM_SCHOOL_ID_SCHOOL_seq"', 1, false);


--
-- TOC entry 5047 (class 0 OID 0)
-- Dependencies: 250
-- Name: EPPM_SCHOOL_ID_SCHOOL_seq1; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."EPPM_SCHOOL_ID_SCHOOL_seq1"', 1, false);


--
-- TOC entry 5048 (class 0 OID 0)
-- Dependencies: 224
-- Name: EPPM_STUDY_PLAN_ID_STUDY_PLAN_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."EPPM_STUDY_PLAN_ID_STUDY_PLAN_seq"', 1, false);


--
-- TOC entry 5049 (class 0 OID 0)
-- Dependencies: 251
-- Name: EPPM_STUDY_PLAN_ID_STUDY_PLAN_seq1; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."EPPM_STUDY_PLAN_ID_STUDY_PLAN_seq1"', 1, false);


--
-- TOC entry 5050 (class 0 OID 0)
-- Dependencies: 228
-- Name: EPPM_TEACHER_ID_TEACHER_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."EPPM_TEACHER_ID_TEACHER_seq"', 1, false);


--
-- TOC entry 5051 (class 0 OID 0)
-- Dependencies: 252
-- Name: EPPM_TEACHER_ID_TEACHER_seq1; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."EPPM_TEACHER_ID_TEACHER_seq1"', 1, false);


--
-- TOC entry 5052 (class 0 OID 0)
-- Dependencies: 232
-- Name: EPPM_USER_ID_USER_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."EPPM_USER_ID_USER_seq"', 1, false);


--
-- TOC entry 5053 (class 0 OID 0)
-- Dependencies: 253
-- Name: EPPM_USER_ID_USER_seq1; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."EPPM_USER_ID_USER_seq1"', 1, true);


--
-- TOC entry 5054 (class 0 OID 0)
-- Dependencies: 242
-- Name: EPPP_PREFERENCES_ID_PREFERENCES_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."EPPP_PREFERENCES_ID_PREFERENCES_seq"', 1, false);


--
-- TOC entry 5055 (class 0 OID 0)
-- Dependencies: 254
-- Name: EPPP_PREFERENCES_ID_PREFERENCES_seq1; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."EPPP_PREFERENCES_ID_PREFERENCES_seq1"', 1, false);


--
-- TOC entry 5056 (class 0 OID 0)
-- Dependencies: 240
-- Name: EPPT_FACULTY_PHONE_ID_FACULTY_PHONE_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."EPPT_FACULTY_PHONE_ID_FACULTY_PHONE_seq"', 1, false);


--
-- TOC entry 5057 (class 0 OID 0)
-- Dependencies: 255
-- Name: EPPT_FACULTY_PHONE_ID_FACULTY_PHONE_seq1; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."EPPT_FACULTY_PHONE_ID_FACULTY_PHONE_seq1"', 1, false);


--
-- TOC entry 5058 (class 0 OID 0)
-- Dependencies: 238
-- Name: EPPT_PHONE_SCHOOL_ID_PHONE_SCHOOL_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."EPPT_PHONE_SCHOOL_ID_PHONE_SCHOOL_seq"', 1, false);


--
-- TOC entry 5059 (class 0 OID 0)
-- Dependencies: 256
-- Name: EPPT_PHONE_SCHOOL_ID_PHONE_SCHOOL_seq1; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."EPPT_PHONE_SCHOOL_ID_PHONE_SCHOOL_seq1"', 1, false);


--
-- TOC entry 5060 (class 0 OID 0)
-- Dependencies: 236
-- Name: EPPT_TEACHER_COURSE_PROGRAM_ID_TEACHER_COUSE_PROGRAM_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."EPPT_TEACHER_COURSE_PROGRAM_ID_TEACHER_COUSE_PROGRAM_seq"', 1, false);


--
-- TOC entry 5061 (class 0 OID 0)
-- Dependencies: 257
-- Name: EPPT_TEACHER_COURSE_PROGRAM_ID_TEACHER_COUSE_PROGRAM_seq1; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."EPPT_TEACHER_COURSE_PROGRAM_ID_TEACHER_COUSE_PROGRAM_seq1"', 1, false);


--
-- TOC entry 4784 (class 2606 OID 16563)
-- Name: EPPM_CAREER PK_CAREER; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."EPPM_CAREER"
    ADD CONSTRAINT "PK_CAREER" PRIMARY KEY ("ID_CAREER");


--
-- TOC entry 4791 (class 2606 OID 16587)
-- Name: EPPM_COURSE_PROGRAM PK_COURSE_PROGRAM; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."EPPM_COURSE_PROGRAM"
    ADD CONSTRAINT "PK_COURSE_PROGRAM" PRIMARY KEY ("ID_COURSE_PROGRAM");


--
-- TOC entry 4780 (class 2606 OID 16589)
-- Name: EPPM_FACULTY PK_FACULTY; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."EPPM_FACULTY"
    ADD CONSTRAINT "PK_FACULTY" PRIMARY KEY ("ID_FACULTY");


--
-- TOC entry 4810 (class 2606 OID 16605)
-- Name: EPPT_FACULTY_PHONE PK_FACULTY_PHONE; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."EPPT_FACULTY_PHONE"
    ADD CONSTRAINT "PK_FACULTY_PHONE" PRIMARY KEY ("ID_FACULTY_PHONE");


--
-- TOC entry 4797 (class 2606 OID 16634)
-- Name: EPPM_PERSON PK_PERSON; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."EPPM_PERSON"
    ADD CONSTRAINT "PK_PERSON" PRIMARY KEY ("ID_PERSON");


--
-- TOC entry 4778 (class 2606 OID 16591)
-- Name: EPPM_PHONE PK_PHONE; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."EPPM_PHONE"
    ADD CONSTRAINT "PK_PHONE" PRIMARY KEY ("ID_PHONE");


--
-- TOC entry 4808 (class 2606 OID 16607)
-- Name: EPPT_PHONE_SCHOOL PK_PHONE_SCHOOL; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."EPPT_PHONE_SCHOOL"
    ADD CONSTRAINT "PK_PHONE_SCHOOL" PRIMARY KEY ("ID_PHONE_SCHOOL");


--
-- TOC entry 4812 (class 2606 OID 16603)
-- Name: EPPP_PREFERENCES PK_PREFERENCES; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."EPPP_PREFERENCES"
    ADD CONSTRAINT "PK_PREFERENCES" PRIMARY KEY ("ID_PREFERENCES");


--
-- TOC entry 4803 (class 2606 OID 16593)
-- Name: EPPM_ROL PK_ROL; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."EPPM_ROL"
    ADD CONSTRAINT "PK_ROL" PRIMARY KEY ("ID_ROL");


--
-- TOC entry 4782 (class 2606 OID 16595)
-- Name: EPPM_SCHOOL PK_SCHOOL; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."EPPM_SCHOOL"
    ADD CONSTRAINT "PK_SCHOOL" PRIMARY KEY ("ID_SCHOOL");


--
-- TOC entry 4787 (class 2606 OID 16597)
-- Name: EPPM_STUDY_PLAN PK_STUDY_PLAN; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."EPPM_STUDY_PLAN"
    ADD CONSTRAINT "PK_STUDY_PLAN" PRIMARY KEY ("ID_STUDY_PLAN");


--
-- TOC entry 4794 (class 2606 OID 16599)
-- Name: EPPM_TEACHER PK_TEACHER; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."EPPM_TEACHER"
    ADD CONSTRAINT "PK_TEACHER" PRIMARY KEY ("ID_TEACHER");


--
-- TOC entry 4805 (class 2606 OID 16609)
-- Name: EPPT_TEACHER_COURSE_PROGRAM PK_TEACHER_COURSE_PROGRAM; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."EPPT_TEACHER_COURSE_PROGRAM"
    ADD CONSTRAINT "PK_TEACHER_COURSE_PROGRAM" PRIMARY KEY ("ID_TEACHER_COUSE_PROGRAM");


--
-- TOC entry 4799 (class 2606 OID 16601)
-- Name: EPPM_USER PK_USER; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."EPPM_USER"
    ADD CONSTRAINT "PK_USER" PRIMARY KEY ("ID_USER");


--
-- TOC entry 4788 (class 1259 OID 16569)
-- Name: fki_FK; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "fki_FK" ON public."EPPM_STUDY_PLAN" USING btree ("ID_CAREER");


--
-- TOC entry 4789 (class 1259 OID 16651)
-- Name: fki_FK_CAREER; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "fki_FK_CAREER" ON public."EPPM_STUDY_PLAN" USING btree ("ID_CAREER");


--
-- TOC entry 4806 (class 1259 OID 16711)
-- Name: fki_FK_COURSE_PROGRAM; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "fki_FK_COURSE_PROGRAM" ON public."EPPT_TEACHER_COURSE_PROGRAM" USING btree ("ID_COURSE_PROGRAM");


--
-- TOC entry 4795 (class 1259 OID 16657)
-- Name: fki_FK_PERSON; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "fki_FK_PERSON" ON public."EPPM_TEACHER" USING btree ("ID_PERSON");


--
-- TOC entry 4813 (class 1259 OID 16674)
-- Name: fki_FK_PREFERENCES; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "fki_FK_PREFERENCES" ON public."EPPP_PREFERENCES" USING btree ("ID_USER");


--
-- TOC entry 4800 (class 1259 OID 16680)
-- Name: fki_FK_PREFERENCES_USER; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "fki_FK_PREFERENCES_USER" ON public."EPPM_USER" USING btree ("ID_PREFERENCES");


--
-- TOC entry 4801 (class 1259 OID 16668)
-- Name: fki_FK_ROL; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "fki_FK_ROL" ON public."EPPM_USER" USING btree ("ID_ROL");


--
-- TOC entry 4785 (class 1259 OID 16558)
-- Name: fki_FK_SCHOOL; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "fki_FK_SCHOOL" ON public."EPPM_CAREER" USING btree ("ID_SCHOOL");


--
-- TOC entry 4792 (class 1259 OID 16626)
-- Name: fki_FK_STUDY_PLAN; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "fki_FK_STUDY_PLAN" ON public."EPPM_COURSE_PROGRAM" USING btree ("ID_STUDY_PLAN");


--
-- TOC entry 4816 (class 2606 OID 16646)
-- Name: EPPM_STUDY_PLAN FK_CAREER; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."EPPM_STUDY_PLAN"
    ADD CONSTRAINT "FK_CAREER" FOREIGN KEY ("ID_CAREER") REFERENCES public."EPPM_CAREER"("ID_CAREER");


--
-- TOC entry 4822 (class 2606 OID 16706)
-- Name: EPPT_TEACHER_COURSE_PROGRAM FK_COURSE_PROGRAM; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."EPPT_TEACHER_COURSE_PROGRAM"
    ADD CONSTRAINT "FK_COURSE_PROGRAM" FOREIGN KEY ("ID_COURSE_PROGRAM") REFERENCES public."EPPM_COURSE_PROGRAM"("ID_COURSE_PROGRAM");


--
-- TOC entry 4814 (class 2606 OID 16641)
-- Name: EPPM_SCHOOL FK_FACULTY; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."EPPM_SCHOOL"
    ADD CONSTRAINT "FK_FACULTY" FOREIGN KEY ("ID_FACULTY") REFERENCES public."EPPM_FACULTY"("ID_FACULTY");


--
-- TOC entry 4826 (class 2606 OID 16681)
-- Name: EPPT_FACULTY_PHONE FK_FACULTY; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."EPPT_FACULTY_PHONE"
    ADD CONSTRAINT "FK_FACULTY" FOREIGN KEY ("ID_FACULTY") REFERENCES public."EPPM_FACULTY"("ID_FACULTY");


--
-- TOC entry 4818 (class 2606 OID 16652)
-- Name: EPPM_TEACHER FK_PERSON; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."EPPM_TEACHER"
    ADD CONSTRAINT "FK_PERSON" FOREIGN KEY ("ID_PERSON") REFERENCES public."EPPM_PERSON"("ID_PERSON");


--
-- TOC entry 4819 (class 2606 OID 16658)
-- Name: EPPM_USER FK_PERSON; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."EPPM_USER"
    ADD CONSTRAINT "FK_PERSON" FOREIGN KEY ("ID_PERSON") REFERENCES public."EPPM_PERSON"("ID_PERSON");


--
-- TOC entry 4827 (class 2606 OID 16686)
-- Name: EPPT_FACULTY_PHONE FK_PHONE; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."EPPT_FACULTY_PHONE"
    ADD CONSTRAINT "FK_PHONE" FOREIGN KEY ("ID_PHONE") REFERENCES public."EPPM_PHONE"("ID_PHONE");


--
-- TOC entry 4824 (class 2606 OID 16696)
-- Name: EPPT_PHONE_SCHOOL FK_PHONE; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."EPPT_PHONE_SCHOOL"
    ADD CONSTRAINT "FK_PHONE" FOREIGN KEY ("ID_PHONE") REFERENCES public."EPPM_PHONE"("ID_PHONE");


--
-- TOC entry 4828 (class 2606 OID 16669)
-- Name: EPPP_PREFERENCES FK_PREFERENCES; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."EPPP_PREFERENCES"
    ADD CONSTRAINT "FK_PREFERENCES" FOREIGN KEY ("ID_USER") REFERENCES public."EPPM_USER"("ID_USER");


--
-- TOC entry 4820 (class 2606 OID 16675)
-- Name: EPPM_USER FK_PREFERENCES_USER; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."EPPM_USER"
    ADD CONSTRAINT "FK_PREFERENCES_USER" FOREIGN KEY ("ID_PREFERENCES") REFERENCES public."EPPP_PREFERENCES"("ID_PREFERENCES");


--
-- TOC entry 4821 (class 2606 OID 16663)
-- Name: EPPM_USER FK_ROL; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."EPPM_USER"
    ADD CONSTRAINT "FK_ROL" FOREIGN KEY ("ID_ROL") REFERENCES public."EPPM_ROL"("ID_ROL");


--
-- TOC entry 4815 (class 2606 OID 16610)
-- Name: EPPM_CAREER FK_SCHOOL; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."EPPM_CAREER"
    ADD CONSTRAINT "FK_SCHOOL" FOREIGN KEY ("ID_SCHOOL") REFERENCES public."EPPM_SCHOOL"("ID_SCHOOL");


--
-- TOC entry 4825 (class 2606 OID 16691)
-- Name: EPPT_PHONE_SCHOOL FK_SCHOOL; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."EPPT_PHONE_SCHOOL"
    ADD CONSTRAINT "FK_SCHOOL" FOREIGN KEY ("ID_SCHOOL") REFERENCES public."EPPM_SCHOOL"("ID_SCHOOL");


--
-- TOC entry 4817 (class 2606 OID 16621)
-- Name: EPPM_COURSE_PROGRAM FK_STUDY_PLAN; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."EPPM_COURSE_PROGRAM"
    ADD CONSTRAINT "FK_STUDY_PLAN" FOREIGN KEY ("ID_STUDY_PLAN") REFERENCES public."EPPM_STUDY_PLAN"("ID_STUDY_PLAN");


--
-- TOC entry 4823 (class 2606 OID 16701)
-- Name: EPPT_TEACHER_COURSE_PROGRAM FK_TEACHER; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."EPPT_TEACHER_COURSE_PROGRAM"
    ADD CONSTRAINT "FK_TEACHER" FOREIGN KEY ("ID_TEACHER") REFERENCES public."EPPM_TEACHER"("ID_TEACHER");


-- Completed on 2024-10-14 16:50:33

--
-- PostgreSQL database dump complete
--

